#ifndef __TIMER1_CONFIG_H__
#define __TIMER1_CONFIG_H__

#include "BitMath.h"
#include "avr/io.h"
#include "avr/interrupt.h"

#define TIMER1_NOMRAL_MODE 1
#define TIMER1_PWM_PHASE_CORRET_MODE 2
#define TIMER1_CTC_MODE 3
#define TIMER1_FAST_PWM_MODE 4

#define TIMER1_MODE TIMER1_NOMRAL_MODE

// desired / overflow time 
#define TIMER1_PRELOAD_VALUE    224
#define TIMER1_OVERFLOW_COUNTER 1952


#define TIMER1_OVER_FLOW_INTERRUPT_ENABLE() (Set_Bit(TIMSK, TOIE1))
#define TIMER1_OVER_FLOW_INTERRUPT_DISABLE() (Clr_Bit(TIMSK, TOIE1))


#define TIMER1_OUTPUT_COMPARE_MATCH_A_INTERRUPT_ENABLE() (Set_Bit(TIMSK, OCIE1A))
#define TIMER1_OUTPUT_COMPARE_MATCH_B_INTERRUPT_ENABLE() (Set_Bit(TIMSK, OCIE1B))

#define TIMER1_OUTPUT_COMPARE_MATCH_A_INTERRUPT_DISABLE() (Clr_Bit(TIMSK, OCIE1A))
#define TIMER1_OUTPUT_COMPARE_MATCH_B_INTERRUPT_DISABLE() (Clr_Bit(TIMSK, OCIE1B))



#endif //__TIMER1_CONFIG_H__